# apiVersion: v1
# kind: Service
# metadata:
#   name: dse-itch-saas
# spec:
#   selector:
#     app: dse-itch-saas
#   type: NodePort
#   ports:
#     - port: 8000
#       targetPort: 8000
#       protocol: TCP
#       nodePort: 30000



# fastapi-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dse-itch-saas-service
spec:
  type: ClusterIP
  selector:
    app: dse-itch-saas
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP