name: CI Pipeline - Automatic Build Python App

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v3

    # - name: Build Docker image
    #   run: |
    #     docker build -t dse_itch_saas:latest .


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOC_USER_NAME }}
          password: ${{ secrets.DOC_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOC_USER_NAME }}/dse_itch_saas:main-${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOC_USER_NAME }}/dse_itch_saas:main-${{ github.sha }}

      - name: Tag latest dev image
        run: |
          docker tag ${{ secrets.DOC_USER_NAME }}/dse_itch_saas:main-${{ github.sha }} ${{ secrets.DOC_USER_NAME }}/dse_itch_saas:main-latest
          docker push ${{ secrets.DOC_USER_NAME }}/dse_itch_saas:main-latest
